export const GAME_TITLE = 'KELİMEBELE'

export const WIN_MESSAGES = ['İnanılmazsın!', 'Muhteşemsin', 'Tebrikler!']
export const GAME_COPIED_MESSAGE = 'Oyun kopyalandı.'
export const ABOUT_GAME_MESSAGE = 'Oyun Hakkında'
export const NOT_ENOUGH_LETTERS_MESSAGE = 'Harf yeterli değil'
export const WORD_NOT_FOUND_MESSAGE = 'Kelime bulunamadı.'
export const CORRECT_WORD_MESSAGE = (solution: string) => `Kelime: ${solution}`
export const ENTER_TEXT = 'Enter'
export const DELETE_TEXT = 'Sil'
export const STATISTICS_TITLE = 'Oyun Durumu'
export const GUESS_DISTRIBUTION_TEXT = 'Tahmin Dağılımı'
export const NEW_WORD_TEXT = 'Yeni Kelime'
export const SHARE_TEXT = 'PAYLAŞ'
export const TOTAL_TRIES_TEXT = 'Oynama Sayısı'
export const SUCCESS_RATE_TEXT = 'Başarı Oranı'
export const CURRENT_STREAK_TEXT = 'Galibiyet Sayısı'
export const BEST_STREAK_TEXT = 'En İyi Galibiyet'
export const NEW_GAME = 'YENİ OYUN'
export const ADS_TEXT = ' yüzlerce haber kaynağı ile gündemi kolayca takip et.'
